version: '3'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    restart: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: RegistroAulas
    volumes:
      - ./db-dump.sql:/docker-entrypoint-initdb.d/db-dump.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:

